site_name: SHOPLINKER 매뉴얼

theme:
  name: null
  custom_dir: 'cinder'
  colorscheme: dracula

extra_css: 
  - css/extra.css

nav :
  - 샵링커 사용법 : 
      - '쇼핑몰 계정세팅' : shoplinker/account.md
      - '그룹관리' : shoplinker/group_set.md
      - '샵링커 상품관리' : shoplinker/sl_product.md
      - '쇼핑몰 상품관리' : shoplinker/mall_product.md
      - '주문관리' : shoplinker/order.md
      - '클레임관리' : shoplinker/claim.md
      - '문의관리' : shoplinker/cs.md
  - 쇼핑몰 안내 : setting.md